### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by TheKhanj** [TheKhanj/yuz#1]
# Tasks
- [x] read `systemd` docs
- [x] ~checkout `daemontools`~
- [ ] write super simple prototype implementation
    - [x] add basic process forking procedure
    - [ ] refactor polymorphic methods in process object
    - [ ] implement simple monitor
    - [ ] add daemon
    - [ ] add cli
- [ ] rewrite and refactor
- [ ] add fancy features
    - [ ] add pre and after hooks
    - [ ] add user and group

**Comment by TheKhanj** [comment]
Just an illustration of what I have in my mind.

![output](https://github.com/TheKhanj/yuz/assets/17639831/ee845d7d-54c2-4ec0-9e3a-fb04279feb34)
